// Copyright (c) Miso Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Independent wire fixtures for every canonical platform decoder.
//
// The inventory below is maintained from the reviewed Move event ABI. It does
// not import generated codecs or derive field order from the codec under test.

import { expect, test } from "bun:test";
import { bcs } from "@mysten/sui/bcs";
import { platformEventParsers } from "../src/events.ts";

type WireToken =
  | "address" | "bool" | "u8" | "u16" | "u32" | "u64" | "u128" | "u256"
  | "string" | "bytes" | "bytes[]" | "bytes[][]"
  | "address[]" | "string[]" | "u64[]" | "u256[]" | "option_u32" | "option_bytes" | "type_name";
type WireField = readonly [name: string, type: WireToken];
type WireFixture = { readonly path: string; readonly name: string; readonly fields: readonly WireField[] };

const EVENT_WIRE_FIXTURES: readonly WireFixture[] = [
  { path: 'extensions.compositionCredits.creditAdded', name: 'CompositionCreditAddedEvent', fields: [
    ['composition_id', 'address'],
    ['composition_admin_cap_id', 'address'],
    ['party_id', 'address'],
    ['display_name', 'bytes'],
    ['role_kinds', 'bytes'],
    ['role_custom_names', 'bytes[]'],
    ['credit_count_before', 'u64'],
    ['credit_count_after', 'u64'],
    ['credit_index', 'u64'],
    ['credits_record_existed_before', 'bool'],
    ['credits_record_exists_after', 'bool'],
  ] },
  { path: 'extensions.compositionCredits.creditRemoved', name: 'CompositionCreditRemovedEvent', fields: [
    ['composition_id', 'address'],
    ['composition_admin_cap_id', 'address'],
    ['party_id', 'address'],
    ['display_name', 'bytes'],
    ['role_kinds', 'bytes'],
    ['role_custom_names', 'bytes[]'],
    ['credit_count_before', 'u64'],
    ['credit_count_after', 'u64'],
    ['credit_index', 'u64'],
    ['credits_record_existed_before', 'bool'],
    ['credits_record_exists_after', 'bool'],
  ] },
  { path: 'extensions.recordingAdvisory.ratingSet', name: 'RecordingAdvisoryRatingSetEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['had_rating', 'bool'],
    ['previous_rating', 'u8'],
    ['rating', 'u8'],
  ] },
  { path: 'extensions.recordingAdvisory.ratingUnset', name: 'RecordingAdvisoryRatingClearedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['previous_rating', 'u8'],
  ] },
  { path: 'extensions.recordingCredits.creditAdded', name: 'CreditAddedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['party_id', 'address'],
    ['display_name', 'bytes'],
    ['role_kinds', 'bytes'],
    ['role_names', 'bytes[]'],
    ['role_instruments', 'bytes[]'],
    ['role_levels', 'bytes'],
    ['credit_index', 'u64'],
    ['credit_count_before', 'u64'],
    ['credit_count_after', 'u64'],
    ['credits_initialized', 'bool'],
  ] },
  { path: 'extensions.recordingCredits.creditRemoved', name: 'CreditRemovedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['party_id', 'address'],
    ['display_name', 'bytes'],
    ['role_kinds', 'bytes'],
    ['role_names', 'bytes[]'],
    ['role_instruments', 'bytes[]'],
    ['role_levels', 'bytes'],
    ['credit_index', 'u64'],
    ['credit_count_before', 'u64'],
    ['credit_count_after', 'u64'],
    ['was_primary_artist', 'bool'],
    ['was_featured_artist', 'bool'],
  ] },
  { path: 'extensions.recordingCredits.primaryArtistAdded', name: 'PrimaryArtistAddedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['party_id', 'address'],
    ['display_name', 'bytes'],
    ['primary_artist_index', 'u64'],
    ['primary_artist_count_before', 'u64'],
    ['primary_artist_count_after', 'u64'],
    ['credit_count_after', 'u64'],
  ] },
  { path: 'extensions.recordingCredits.primaryArtistRemoved', name: 'PrimaryArtistRemovedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['party_id', 'address'],
    ['display_name', 'bytes'],
    ['primary_artist_index', 'u64'],
    ['primary_artist_count_before', 'u64'],
    ['primary_artist_count_after', 'u64'],
    ['credit_count_after', 'u64'],
    ['caused_by_credit_removal', 'bool'],
  ] },
  { path: 'extensions.recordingCredits.featuredArtistAdded', name: 'FeaturedArtistAddedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['party_id', 'address'],
    ['display_name', 'bytes'],
    ['featured_artist_index', 'u64'],
    ['featured_artist_count_before', 'u64'],
    ['featured_artist_count_after', 'u64'],
    ['credit_count_after', 'u64'],
  ] },
  { path: 'extensions.recordingCredits.featuredArtistRemoved', name: 'FeaturedArtistRemovedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['party_id', 'address'],
    ['display_name', 'bytes'],
    ['featured_artist_index', 'u64'],
    ['featured_artist_count_before', 'u64'],
    ['featured_artist_count_after', 'u64'],
    ['credit_count_after', 'u64'],
    ['caused_by_credit_removal', 'bool'],
  ] },
  { path: 'extensions.recordingEngineSession.set', name: 'EngineSessionSetEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['had_previous', 'bool'],
    ['value_changed', 'bool'],
    ['previous_session_blob_id', 'u256'],
    ['previous_stem_count', 'u64'],
    ['session_blob_id', 'u256'],
    ['stem_count', 'u64'],
    ['stem_digests', 'bytes[]'],
    ['stem_blob_ids', 'u256[]'],
  ] },
  { path: 'extensions.recordingEngineSession.unset', name: 'EngineSessionUnsetEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['removed_session_blob_id', 'u256'],
    ['removed_stem_count', 'u64'],
    ['removed_stem_digests', 'bytes[]'],
    ['removed_stem_blob_ids', 'u256[]'],
  ] },
  { path: 'extensions.recordingGenre.genreAdded', name: 'RecordingGenreAddedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['genre_id', 'address'],
    ['genre_name', 'bytes'],
    ['genre_index', 'u64'],
    ['genres_before', 'address[]'],
    ['genres_after', 'address[]'],
    ['genre_count_before', 'u64'],
    ['genre_count_after', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['had_primary_before', 'bool'],
    ['has_primary_after', 'bool'],
    ['primary_genre_id_before', 'address'],
    ['primary_genre_id_after', 'address'],
    ['primary_changed', 'bool'],
  ] },
  { path: 'extensions.recordingGenre.genreRemoved', name: 'RecordingGenreRemovedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['genre_id', 'address'],
    ['genre_index', 'u64'],
    ['genres_before', 'address[]'],
    ['genres_after', 'address[]'],
    ['genre_count_before', 'u64'],
    ['genre_count_after', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['had_primary_before', 'bool'],
    ['has_primary_after', 'bool'],
    ['primary_genre_id_before', 'address'],
    ['primary_genre_id_after', 'address'],
    ['primary_changed', 'bool'],
  ] },
  { path: 'extensions.recordingGenre.genresCleared', name: 'RecordingGenresClearedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['clear_cause', 'u8'],
    ['trigger_genre_id', 'address'],
    ['genres_before', 'address[]'],
    ['genres_after', 'address[]'],
    ['genre_count_before', 'u64'],
    ['genre_count_after', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['had_primary_before', 'bool'],
    ['has_primary_after', 'bool'],
    ['primary_genre_id_before', 'address'],
    ['primary_genre_id_after', 'address'],
    ['primary_changed', 'bool'],
  ] },
  { path: 'extensions.recordingLanguage.languagesSet', name: 'RecordingLanguagesSetEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['had_languages', 'bool'],
    ['previous_languages', 'bytes[]'],
    ['languages', 'bytes[]'],
    ['language_count_before', 'u64'],
    ['language_count_after', 'u64'],
    ['was_instrumental', 'bool'],
    ['is_instrumental', 'bool'],
    ['max_languages', 'u64'],
  ] },
  { path: 'extensions.recordingLanguage.languagesUnset', name: 'RecordingLanguagesClearedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['removed_languages', 'bytes[]'],
    ['language_count_before', 'u64'],
    ['was_instrumental', 'bool'],
  ] },
  { path: 'extensions.recordingMasterReference.masterReferenceSet', name: 'RecordingMasterReferenceSetEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['had_master_reference', 'bool'],
    ['previous_blob_id', 'u256'],
    ['previous_is_encrypted', 'bool'],
    ['previous_sealed_dek_length', 'u64'],
    ['previous_sealed_dek_digest', 'bytes'],
    ['blob_id', 'u256'],
    ['is_encrypted', 'bool'],
    ['sealed_dek_length', 'u64'],
    ['sealed_dek_digest', 'bytes'],
  ] },
  { path: 'extensions.recordingMasterReference.masterReferenceUnset', name: 'RecordingMasterReferenceClearedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['removed_blob_id', 'u256'],
    ['removed_is_encrypted', 'bool'],
    ['removed_sealed_dek_length', 'u64'],
    ['removed_sealed_dek_digest', 'bytes'],
  ] },
  { path: 'extensions.recordingStreamingTranscode.set', name: 'RecordingStreamingTranscodeSetEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['had_transcode', 'bool'],
    ['previous_quilt_id', 'u256'],
    ['quilt_id', 'u256'],
  ] },
  { path: 'extensions.recordingStreamingTranscode.cleared', name: 'RecordingStreamingTranscodeClearedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['quilt_id', 'u256'],
  ] },
  { path: 'extensions.releaseCoverArt.coverSet', name: 'ReleaseCoverArtSetEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['track_count', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['previous_present', 'bool'],
    ['previous_still_blob_id', 'u256'],
    ['previous_still_is_encrypted', 'bool'],
    ['previous_still_sealed_dek_length', 'u64'],
    ['previous_still_sealed_dek_digest', 'bytes'],
    ['previous_has_animated', 'bool'],
    ['previous_animated_blob_id', 'u256'],
    ['previous_animated_is_encrypted', 'bool'],
    ['previous_animated_sealed_dek_length', 'u64'],
    ['previous_animated_sealed_dek_digest', 'bytes'],
    ['current_present', 'bool'],
    ['current_still_blob_id', 'u256'],
    ['current_still_is_encrypted', 'bool'],
    ['current_still_sealed_dek_length', 'u64'],
    ['current_still_sealed_dek_digest', 'bytes'],
    ['current_has_animated', 'bool'],
    ['current_animated_blob_id', 'u256'],
    ['current_animated_is_encrypted', 'bool'],
    ['current_animated_sealed_dek_length', 'u64'],
    ['current_animated_sealed_dek_digest', 'bytes'],
  ] },
  { path: 'extensions.releaseCoverArt.coverUnset', name: 'ReleaseCoverArtUnsetEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['track_count', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['previous_present', 'bool'],
    ['previous_still_blob_id', 'u256'],
    ['previous_still_is_encrypted', 'bool'],
    ['previous_still_sealed_dek_length', 'u64'],
    ['previous_still_sealed_dek_digest', 'bytes'],
    ['previous_has_animated', 'bool'],
    ['previous_animated_blob_id', 'u256'],
    ['previous_animated_is_encrypted', 'bool'],
    ['previous_animated_sealed_dek_length', 'u64'],
    ['previous_animated_sealed_dek_digest', 'bytes'],
    ['current_present', 'bool'],
    ['current_still_blob_id', 'u256'],
    ['current_still_is_encrypted', 'bool'],
    ['current_still_sealed_dek_length', 'u64'],
    ['current_still_sealed_dek_digest', 'bytes'],
    ['current_has_animated', 'bool'],
    ['current_animated_blob_id', 'u256'],
    ['current_animated_is_encrypted', 'bool'],
    ['current_animated_sealed_dek_length', 'u64'],
    ['current_animated_sealed_dek_digest', 'bytes'],
  ] },
  { path: 'extensions.releaseCoverArt.trackCoverSet', name: 'ReleaseTrackCoverArtSetEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['track_count', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['track_index', 'u64'],
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['previous_present', 'bool'],
    ['previous_still_blob_id', 'u256'],
    ['previous_still_is_encrypted', 'bool'],
    ['previous_still_sealed_dek_length', 'u64'],
    ['previous_still_sealed_dek_digest', 'bytes'],
    ['previous_has_animated', 'bool'],
    ['previous_animated_blob_id', 'u256'],
    ['previous_animated_is_encrypted', 'bool'],
    ['previous_animated_sealed_dek_length', 'u64'],
    ['previous_animated_sealed_dek_digest', 'bytes'],
    ['current_present', 'bool'],
    ['current_still_blob_id', 'u256'],
    ['current_still_is_encrypted', 'bool'],
    ['current_still_sealed_dek_length', 'u64'],
    ['current_still_sealed_dek_digest', 'bytes'],
    ['current_has_animated', 'bool'],
    ['current_animated_blob_id', 'u256'],
    ['current_animated_is_encrypted', 'bool'],
    ['current_animated_sealed_dek_length', 'u64'],
    ['current_animated_sealed_dek_digest', 'bytes'],
    ['album_present', 'bool'],
    ['album_still_blob_id', 'u256'],
    ['album_still_is_encrypted', 'bool'],
    ['album_still_sealed_dek_length', 'u64'],
    ['album_still_sealed_dek_digest', 'bytes'],
    ['album_has_animated', 'bool'],
    ['album_animated_blob_id', 'u256'],
    ['album_animated_is_encrypted', 'bool'],
    ['album_animated_sealed_dek_length', 'u64'],
    ['album_animated_sealed_dek_digest', 'bytes'],
  ] },
  { path: 'extensions.releaseCoverArt.trackCoverUnset', name: 'ReleaseTrackCoverArtUnsetEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['track_count', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['track_index', 'u64'],
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['previous_present', 'bool'],
    ['previous_still_blob_id', 'u256'],
    ['previous_still_is_encrypted', 'bool'],
    ['previous_still_sealed_dek_length', 'u64'],
    ['previous_still_sealed_dek_digest', 'bytes'],
    ['previous_has_animated', 'bool'],
    ['previous_animated_blob_id', 'u256'],
    ['previous_animated_is_encrypted', 'bool'],
    ['previous_animated_sealed_dek_length', 'u64'],
    ['previous_animated_sealed_dek_digest', 'bytes'],
    ['current_present', 'bool'],
    ['current_still_blob_id', 'u256'],
    ['current_still_is_encrypted', 'bool'],
    ['current_still_sealed_dek_length', 'u64'],
    ['current_still_sealed_dek_digest', 'bytes'],
    ['current_has_animated', 'bool'],
    ['current_animated_blob_id', 'u256'],
    ['current_animated_is_encrypted', 'bool'],
    ['current_animated_sealed_dek_length', 'u64'],
    ['current_animated_sealed_dek_digest', 'bytes'],
    ['album_present', 'bool'],
    ['album_still_blob_id', 'u256'],
    ['album_still_is_encrypted', 'bool'],
    ['album_still_sealed_dek_length', 'u64'],
    ['album_still_sealed_dek_digest', 'bytes'],
    ['album_has_animated', 'bool'],
    ['album_animated_blob_id', 'u256'],
    ['album_animated_is_encrypted', 'bool'],
    ['album_animated_sealed_dek_length', 'u64'],
    ['album_animated_sealed_dek_digest', 'bytes'],
  ] },
  { path: 'extensions.releaseCredits.creditAdded', name: 'ReleaseCreditAddedEvent', fields: [
    ['release_id', 'address'],
    ['release_admin_cap_id', 'address'],
    ['party_id', 'address'],
    ['display_name', 'bytes'],
    ['role_kind', 'u8'],
    ['credit_count_before', 'u64'],
    ['credit_count_after', 'u64'],
    ['credit_index', 'u64'],
    ['credits_record_existed_before', 'bool'],
    ['credits_record_exists_after', 'bool'],
  ] },
  { path: 'extensions.releaseCredits.creditRemoved', name: 'ReleaseCreditRemovedEvent', fields: [
    ['release_id', 'address'],
    ['release_admin_cap_id', 'address'],
    ['party_id', 'address'],
    ['display_name', 'bytes'],
    ['role_kind', 'u8'],
    ['credit_count_before', 'u64'],
    ['credit_count_after', 'u64'],
    ['credit_index', 'u64'],
    ['credits_record_existed_before', 'bool'],
    ['credits_record_exists_after', 'bool'],
  ] },
  { path: 'extensions.releaseDescription.descriptionSet', name: 'ReleaseDescriptionSetEvent', fields: [
    ['release_id', 'address'],
    ['release_admin_cap_id', 'address'],
    ['description_existed_before', 'bool'],
    ['description_before', 'bytes'],
    ['description_after', 'bytes'],
  ] },
  { path: 'extensions.releaseDescription.descriptionCleared', name: 'ReleaseDescriptionClearedEvent', fields: [
    ['release_id', 'address'],
    ['release_admin_cap_id', 'address'],
    ['description_before', 'bytes'],
  ] },
  { path: 'extensions.releaseDspLink.releaseLinkSet', name: 'ReleaseDspLinkSetEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['platform', 'u8'],
    ['track_count', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['previous_present', 'bool'],
    ['previous_fields', 'bytes[]'],
    ['current_present', 'bool'],
    ['current_fields', 'bytes[]'],
  ] },
  { path: 'extensions.releaseDspLink.releaseLinkCleared', name: 'ReleaseDspLinkClearedEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['platform', 'u8'],
    ['track_count', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['previous_present', 'bool'],
    ['previous_fields', 'bytes[]'],
    ['current_present', 'bool'],
    ['current_fields', 'bytes[]'],
  ] },
  { path: 'extensions.releaseDspLink.trackLinkSet', name: 'ReleaseTrackDspLinkSetEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['platform', 'u8'],
    ['track_count', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['track_index', 'u64'],
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['previous_present', 'bool'],
    ['previous_fields', 'bytes[]'],
    ['current_present', 'bool'],
    ['current_fields', 'bytes[]'],
    ['album_present', 'bool'],
    ['album_fields', 'bytes[]'],
  ] },
  { path: 'extensions.releaseDspLink.trackLinkCleared', name: 'ReleaseTrackDspLinkClearedEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['platform', 'u8'],
    ['track_count', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['track_index', 'u64'],
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['previous_present', 'bool'],
    ['previous_fields', 'bytes[]'],
    ['current_present', 'bool'],
    ['current_fields', 'bytes[]'],
    ['album_present', 'bool'],
    ['album_fields', 'bytes[]'],
  ] },
  { path: 'extensions.releaseDspLink.trackLinksCleared', name: 'ReleaseTrackDspLinksClearedEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['platform', 'u8'],
    ['track_count', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['removed_link_count', 'u64'],
    ['removed_track_indices', 'u64[]'],
    ['removed_recording_ids', 'address[]'],
    ['removed_composition_ids', 'address[]'],
    ['removed_link_fields', 'bytes[][]'],
    ['album_present', 'bool'],
    ['album_fields', 'bytes[]'],
  ] },
  { path: 'extensions.releaseGenre.genreAdded', name: 'ReleaseGenreAddedEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['genre_id', 'address'],
    ['genre_name', 'bytes'],
    ['genre_index', 'u64'],
    ['genres_before', 'address[]'],
    ['genres_after', 'address[]'],
    ['genre_count_before', 'u64'],
    ['genre_count_after', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['had_primary_before', 'bool'],
    ['has_primary_after', 'bool'],
    ['primary_genre_id_before', 'address'],
    ['primary_genre_id_after', 'address'],
    ['primary_changed', 'bool'],
  ] },
  { path: 'extensions.releaseGenre.genreRemoved', name: 'ReleaseGenreRemovedEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['genre_id', 'address'],
    ['genre_index', 'u64'],
    ['genres_before', 'address[]'],
    ['genres_after', 'address[]'],
    ['genre_count_before', 'u64'],
    ['genre_count_after', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['had_primary_before', 'bool'],
    ['has_primary_after', 'bool'],
    ['primary_genre_id_before', 'address'],
    ['primary_genre_id_after', 'address'],
    ['primary_changed', 'bool'],
  ] },
  { path: 'extensions.releaseGenre.genresCleared', name: 'ReleaseGenresClearedEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['clear_cause', 'u8'],
    ['trigger_genre_id', 'address'],
    ['genres_before', 'address[]'],
    ['genres_after', 'address[]'],
    ['genre_count_before', 'u64'],
    ['genre_count_after', 'u64'],
    ['field_existed_before', 'bool'],
    ['field_exists_after', 'bool'],
    ['had_primary_before', 'bool'],
    ['has_primary_after', 'bool'],
    ['primary_genre_id_before', 'address'],
    ['primary_genre_id_after', 'address'],
    ['primary_changed', 'bool'],
  ] },
  { path: 'extensions.releaseKind.kindSet', name: 'ReleaseKindSetEvent', fields: [
    ['release_id', 'address'],
    ['release_admin_cap_id', 'address'],
    ['kind_record_existed_before', 'bool'],
    ['previous_kind', 'bytes'],
    ['previous_kind_length', 'u64'],
    ['kind', 'bytes'],
    ['kind_length', 'u64'],
    ['kind_record_exists_after', 'bool'],
    ['kind_changed', 'bool'],
  ] },
  { path: 'extensions.releaseKind.kindUnset', name: 'ReleaseKindUnsetEvent', fields: [
    ['release_id', 'address'],
    ['release_admin_cap_id', 'address'],
    ['kind_record_existed_before', 'bool'],
    ['previous_kind', 'bytes'],
    ['previous_kind_length', 'u64'],
    ['kind', 'bytes'],
    ['kind_length', 'u64'],
    ['kind_record_exists_after', 'bool'],
    ['kind_changed', 'bool'],
  ] },
  { path: 'extensions.partyCta.set', name: 'CtasSetEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['existed_before', 'bool'],
    ['previous_count', 'u64'],
    ['count', 'u64'],
    ['previous_labels', 'bytes[]'],
    ['previous_urls', 'bytes[]'],
    ['labels', 'bytes[]'],
    ['urls', 'bytes[]'],
  ] },
  { path: 'extensions.partyCta.cleared', name: 'CtasClearedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['previous_count', 'u64'],
    ['previous_labels', 'bytes[]'],
    ['previous_urls', 'bytes[]'],
  ] },
  { path: 'extensions.partyGenre.added', name: 'GenreAddedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['genre_id', 'address'],
    ['genre_name', 'bytes'],
    ['genre_ids_before', 'address[]'],
    ['genre_ids_after', 'address[]'],
    ['max_genres', 'u64'],
  ] },
  { path: 'extensions.partyGenre.removed', name: 'GenreRemovedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['genre_id', 'address'],
    ['genre_ids_before', 'address[]'],
    ['genre_ids_after', 'address[]'],
  ] },
  { path: 'extensions.partyGenre.cleared', name: 'GenresClearedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['genre_ids_before', 'address[]'],
    ['genre_ids_after', 'address[]'],
  ] },
  { path: 'extensions.partyMedia.set', name: 'MediaSetEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['existed_before', 'bool'],
    ['previous_quilt', 'u256'],
    ['quilt', 'u256'],
  ] },
  { path: 'extensions.partyMedia.cleared', name: 'MediaClearedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['previous_quilt', 'u256'],
  ] },
  { path: 'extensions.partyPlatformLink.legacy.set', name: 'LinkSetEvent', fields: [
    ['party_id', 'address'],
  ] },
  { path: 'extensions.partyPlatformLink.legacy.cleared', name: 'LinkClearedEvent', fields: [
    ['party_id', 'address'],
  ] },
  { path: 'extensions.partyProfile.set', name: 'PartyProfileSetEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['had_profile', 'bool'],
    ['previous_bio_short', 'bytes'],
    ['previous_bio_long', 'option_bytes'],
    ['previous_country', 'option_bytes'],
    ['previous_languages', 'bytes[]'],
    ['bio_short', 'bytes'],
    ['bio_long', 'option_bytes'],
    ['country', 'option_bytes'],
    ['languages', 'bytes[]'],
  ] },
  { path: 'extensions.partyProfile.cleared', name: 'PartyProfileClearedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['previous_bio_short', 'bytes'],
    ['previous_bio_long', 'option_bytes'],
    ['previous_country', 'option_bytes'],
    ['previous_languages', 'bytes[]'],
  ] },
  { path: 'extensions.partyRoles.added', name: 'RoleAddedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['role_kind', 'u8'],
    ['role_name', 'bytes'],
    ['roles_count_before', 'u64'],
    ['roles_count_after', 'u64'],
  ] },
  { path: 'extensions.partyRoles.removed', name: 'RoleRemovedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['role_kind', 'u8'],
    ['role_name', 'bytes'],
    ['roles_count_before', 'u64'],
    ['roles_count_after', 'u64'],
  ] },
  { path: 'extensions.partyRoles.cleared', name: 'RolesClearedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['removed_role_kinds', 'bytes'],
    ['removed_role_names', 'bytes[]'],
    ['roles_count_before', 'u64'],
    ['roles_count_after', 'u64'],
  ] },
  { path: 'extensions.partyTags.added', name: 'TagAddedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['tag', 'bytes'],
    ['tag_count_before', 'u64'],
    ['tag_count_after', 'u64'],
  ] },
  { path: 'extensions.partyTags.removed', name: 'TagRemovedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['tag', 'bytes'],
    ['tag_count_before', 'u64'],
    ['tag_count_after', 'u64'],
  ] },
  { path: 'extensions.partyTags.cleared', name: 'TagsClearedEvent', fields: [
    ['party_id', 'address'],
    ['admin_cap_id', 'address'],
    ['removed_tags', 'bytes[]'],
    ['tag_count_before', 'u64'],
    ['tag_count_after', 'u64'],
  ] },
  { path: 'primitives.royaltyPool.poolCreated', name: 'RoyaltyPoolCreatedEvent', fields: [
    ['pool_id', 'address'],
    ['parent_id', 'address'],
    ['precision', 'u128'],
    ['pool_balance_after', 'u64'],
    ['staked_shares_after', 'u64'],
    ['cumulative_reward_per_share_after', 'u256'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_after', 'u128'],
  ] },
  { path: 'primitives.royaltyPool.poolShared', name: 'RoyaltyPoolSharedEvent', fields: [
    ['pool_id', 'address'],
    ['pool_balance_after', 'u64'],
    ['staked_shares_after', 'u64'],
    ['cumulative_reward_per_share_after', 'u256'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_after', 'u128'],
  ] },
  { path: 'primitives.royaltyPool.deposited', name: 'RoyaltyDepositedEvent', fields: [
    ['pool_id', 'address'],
    ['value', 'u64'],
    ['cumulative_reward_per_share_before', 'u256'],
    ['carry_before', 'u128'],
    ['pool_balance_after', 'u64'],
    ['staked_shares_after', 'u64'],
    ['cumulative_reward_per_share_after', 'u256'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_after', 'u128'],
  ] },
  { path: 'primitives.royaltyPool.fundsSettled', name: 'RoyaltyPoolFundsSettledEvent', fields: [
    ['pool_id', 'address'],
    ['source_address', 'address'],
    ['accumulator_root_id', 'address'],
    ['value', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares_after', 'u64'],
    ['cumulative_reward_per_share_after', 'u256'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_after', 'u128'],
  ] },
  { path: 'primitives.royaltyPool.coinsRecovered', name: 'RoyaltyPoolCoinsRecoveredEvent', fields: [
    ['pool_id', 'address'],
    ['coin_ids', 'address[]'],
    ['coin_count', 'u64'],
    ['funds_recipient', 'address'],
    ['value', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares_after', 'u64'],
    ['cumulative_reward_per_share_after', 'u256'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_after', 'u128'],
  ] },
  { path: 'primitives.royaltyPool.stakeRegistered', name: 'StakeRegisteredEvent', fields: [
    ['pool_id', 'address'],
    ['stake_id', 'address'],
    ['staked_amount', 'u64'],
    ['registration_debt_after', 'u256'],
    ['stake_registration_count_after', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares_after', 'u64'],
    ['cumulative_reward_per_share_after', 'u256'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_after', 'u128'],
  ] },
  { path: 'primitives.royaltyPool.stakeUnregistered', name: 'StakeUnregisteredEvent', fields: [
    ['pool_id', 'address'],
    ['stake_id', 'address'],
    ['unstaked_amount', 'u64'],
    ['removed_registration_debt', 'u256'],
    ['forfeited_reward_numerator', 'u256'],
    ['stake_registration_count_after', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares_after', 'u64'],
    ['cumulative_reward_per_share_after', 'u256'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_after', 'u128'],
  ] },
  { path: 'primitives.royaltyPool.royaltyClaimed', name: 'RoyaltyClaimedEvent', fields: [
    ['pool_id', 'address'],
    ['stake_id', 'address'],
    ['staked_amount', 'u64'],
    ['reward_amount', 'u64'],
    ['registration_debt_before', 'u256'],
    ['registration_debt_after', 'u256'],
    ['reward_residue_after', 'u256'],
    ['stake_registration_count_after', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares_after', 'u64'],
    ['cumulative_reward_per_share_after', 'u256'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_after', 'u128'],
  ] },
  { path: 'primitives.royaltyPool.stakeCreated', name: 'StakeCreatedEvent', fields: [
    ['stake_id', 'address'],
    ['transaction_sender', 'address'],
    ['amount', 'u64'],
    ['registration_count_after', 'u64'],
  ] },
  { path: 'primitives.royaltyPool.stakeDestroyed', name: 'StakeDestroyedEvent', fields: [
    ['stake_id', 'address'],
    ['amount', 'u64'],
    ['registration_count_before', 'u64'],
  ] },
  { path: 'primitives.routedStake.created', name: 'RoutedStakeCreatedEvent', fields: [
    ['routed_stake_id', 'address'],
    ['parent_id', 'address'],
    ['stake_id', 'address'],
    ['staked_value', 'u64'],
  ] },
  { path: 'primitives.routedStake.shared', name: 'RoutedStakeSharedEvent', fields: [
    ['routed_stake_id', 'address'],
    ['has_stake', 'bool'],
    ['stake_id', 'address'],
    ['staked_value', 'u64'],
    ['registration_count', 'u64'],
  ] },
  { path: 'primitives.routedStake.registered', name: 'RoutedStakeRegisteredEvent', fields: [
    ['routed_stake_id', 'address'],
    ['parent_id', 'address'],
    ['stake_id', 'address'],
    ['stake_pool_id', 'address'],
    ['staked_value', 'u64'],
    ['registration_count_before', 'u64'],
    ['registration_count_after', 'u64'],
    ['pool_staked_shares_before', 'u64'],
    ['pool_staked_shares_after', 'u64'],
    ['pool_cumulative_reward_per_share', 'u256'],
    ['registration_debt_after', 'u256'],
  ] },
  { path: 'primitives.routedStake.unregistered', name: 'RoutedStakeUnregisteredEvent', fields: [
    ['routed_stake_id', 'address'],
    ['parent_id', 'address'],
    ['stake_id', 'address'],
    ['stake_pool_id', 'address'],
    ['staked_value', 'u64'],
    ['registration_count_before', 'u64'],
    ['registration_count_after', 'u64'],
    ['pool_staked_shares_before', 'u64'],
    ['pool_staked_shares_after', 'u64'],
    ['pool_cumulative_reward_per_share', 'u256'],
    ['registration_debt_before', 'u256'],
  ] },
  { path: 'primitives.routedStake.swept', name: 'RoutedStakeSweptEvent', fields: [
    ['routed_stake_id', 'address'],
    ['parent_id', 'address'],
    ['stake_id', 'address'],
    ['stake_pool_id', 'address'],
    ['routed_pool_id', 'address'],
    ['value', 'u64'],
    ['parked', 'bool'],
    ['staked_value', 'u64'],
    ['source_balance_before', 'u64'],
    ['source_balance_after', 'u64'],
    ['source_staked_shares', 'u64'],
    ['source_index', 'u256'],
    ['source_carry', 'u128'],
    ['source_cumulative_deposits', 'u128'],
    ['registration_debt_before', 'u256'],
    ['registration_debt_after', 'u256'],
    ['destination_balance_before', 'u64'],
    ['destination_balance_after', 'u64'],
    ['destination_staked_shares', 'u64'],
    ['destination_index_before', 'u256'],
    ['destination_index_after', 'u256'],
    ['destination_carry_before', 'u128'],
    ['destination_carry_after', 'u128'],
    ['destination_cumulative_deposits_before', 'u128'],
    ['destination_cumulative_deposits_after', 'u128'],
  ] },
  { path: 'primitives.routedStake.unstaked', name: 'RoutedStakeUnstakedEvent', fields: [
    ['routed_stake_id', 'address'],
    ['parent_id', 'address'],
    ['stake_id', 'address'],
    ['unstaked_value', 'u64'],
  ] },
  { path: 'primitives.routedStake.restaked', name: 'RoutedStakeRestakedEvent', fields: [
    ['routed_stake_id', 'address'],
    ['parent_id', 'address'],
    ['stake_id', 'address'],
    ['staked_value', 'u64'],
  ] },
  { path: 'primitives.vault.registryCreated', name: 'VaultRegistryCreatedEvent', fields: [
    ['registry_id', 'address'],
    ['shared', 'bool'],
  ] },
  { path: 'primitives.vault.created', name: 'VaultCreatedEvent', fields: [
    ['registry_id', 'address'],
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['admin_cap_id', 'address'],
    ['authorized_plugins_id', 'address'],
    ['authorized_plugin_count', 'u64'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
  ] },
  { path: 'primitives.vault.shared', name: 'VaultSharedEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
  ] },
  { path: 'primitives.vault.pluginAuthorized', name: 'PluginAuthorizedEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['admin_cap_id', 'address'],
    ['authorized_plugins_id', 'address'],
    ['authorized_plugin_count', 'u64'],
    ['authorized', 'bool'],
  ] },
  { path: 'primitives.vault.pluginRevoked', name: 'PluginRevokedEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['admin_cap_id', 'address'],
    ['authorized_plugins_id', 'address'],
    ['authorized_plugin_count', 'u64'],
    ['authorized', 'bool'],
  ] },
  { path: 'primitives.vault.capabilityWithdrawn', name: 'VaultCapabilityWithdrawnEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['admin_cap_id', 'address'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
  ] },
  { path: 'primitives.vault.capabilityRestored', name: 'VaultCapabilityRestoredEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['admin_cap_id', 'address'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
  ] },
  { path: 'primitives.vault.capabilityBorrowedByPlugin', name: 'VaultCapabilityBorrowedByPluginEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
  ] },
  { path: 'primitives.vault.capabilityBorrowedByAdmin', name: 'VaultCapabilityBorrowedByAdminEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['admin_cap_id', 'address'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
  ] },
  { path: 'primitives.vault.capabilityReturned', name: 'VaultCapabilityReturnedEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
  ] },
  { path: 'primitives.genre.registryCreated', name: 'GenreRegistryCreatedEvent', fields: [
    ['registry_id', 'address'],
    ['initializer', 'address'],
    ['is_shared', 'bool'],
  ] },
  { path: 'primitives.genre.created', name: 'GenreCreatedEvent', fields: [
    ['registry_id', 'address'],
    ['genre_id', 'address'],
    ['name', 'bytes'],
    ['is_frozen', 'bool'],
  ] },
  { path: 'primitives.platformLink.set', name: 'PlatformLinkSetEvent', fields: [
    ['parent_id', 'address'],
    ['data_type', 'bytes'],
    ['existed_before', 'bool'],
    ['exists_after', 'bool'],
    ['previous_bcs_length', 'u64'],
    ['previous_bcs_hash', 'bytes'],
    ['data_bcs_length', 'u64'],
    ['data_bcs_hash', 'bytes'],
  ] },
  { path: 'primitives.platformLink.removed', name: 'PlatformLinkRemovedEvent', fields: [
    ['parent_id', 'address'],
    ['data_type', 'bytes'],
    ['existed_before', 'bool'],
    ['exists_after', 'bool'],
    ['removed_bcs_length', 'u64'],
    ['removed_bcs_hash', 'bytes'],
  ] },
  { path: 'primitives.share.initialized', name: 'ShareInitializedEvent', fields: [
    ['currency_id', 'address'],
    ['treasury_cap_id', 'address'],
    ['share_type', 'bytes'],
    ['decimals', 'u8'],
    ['supply', 'u64'],
    ['fixed_supply', 'bool'],
    ['metadata_cap_deleted', 'bool'],
    ['regulated', 'bool'],
    ['name', 'bytes'],
    ['symbol', 'bytes'],
    ['description', 'bytes'],
    ['icon_url', 'bytes'],
  ] },
  { path: 'actions.compositionRoyaltyPool.poolCreated', name: 'CompositionRoyaltyPoolCreatedEvent', fields: [
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['pool_id', 'address'],
    ['pool_balance', 'u64'],
    ['staked_shares', 'u64'],
    ['cumulative_reward_per_share', 'u256'],
    ['carry', 'u128'],
    ['cumulative_deposits', 'u128'],
  ] },
  { path: 'actions.compositionRoyaltyPool.coinsDeposited', name: 'CompositionCoinsDepositedEvent', fields: [
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['pool_id', 'address'],
    ['amount', 'u64'],
    ['pool_balance_before', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares', 'u64'],
    ['reward_per_share_before', 'u256'],
    ['reward_per_share_after', 'u256'],
    ['carry_before', 'u128'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_before', 'u128'],
    ['cumulative_deposits_after', 'u128'],
    ['coin_ids', 'address[]'],
  ] },
  { path: 'actions.compositionRoyaltyPool.fundsDeposited', name: 'CompositionFundsDepositedEvent', fields: [
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['pool_id', 'address'],
    ['amount', 'u64'],
    ['pool_balance_before', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares', 'u64'],
    ['reward_per_share_before', 'u256'],
    ['reward_per_share_after', 'u256'],
    ['carry_before', 'u128'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_before', 'u128'],
    ['cumulative_deposits_after', 'u128'],
  ] },
  { path: 'actions.recordingRoyaltyPool.poolCreated', name: 'RecordingRoyaltyPoolCreatedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['pool_id', 'address'],
    ['pool_balance', 'u64'],
    ['staked_shares', 'u64'],
    ['cumulative_reward_per_share', 'u256'],
    ['carry', 'u128'],
    ['cumulative_deposits', 'u128'],
  ] },
  { path: 'actions.recordingRoyaltyPool.coinsDeposited', name: 'RecordingCoinsDepositedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['pool_id', 'address'],
    ['amount', 'u64'],
    ['pool_balance_before', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares', 'u64'],
    ['reward_per_share_before', 'u256'],
    ['reward_per_share_after', 'u256'],
    ['carry_before', 'u128'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_before', 'u128'],
    ['cumulative_deposits_after', 'u128'],
    ['coin_ids', 'address[]'],
  ] },
  { path: 'actions.recordingRoyaltyPool.fundsDeposited', name: 'RecordingFundsDepositedEvent', fields: [
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['pool_id', 'address'],
    ['amount', 'u64'],
    ['pool_balance_before', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares', 'u64'],
    ['reward_per_share_before', 'u256'],
    ['reward_per_share_after', 'u256'],
    ['carry_before', 'u128'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_before', 'u128'],
    ['cumulative_deposits_after', 'u128'],
  ] },
  { path: 'actions.compositionRoutedStake.created', name: 'CompositionRoutedStakeCreatedEvent', fields: [
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['recording_id', 'address'],
    ['routed_stake_id', 'address'],
    ['stake_id', 'address'],
    ['sender', 'address'],
    ['principal_value', 'u64'],
    ['registration_count', 'u64'],
  ] },
  { path: 'actions.compositionRoutedStake.registered', name: 'CompositionRoutedStakeRegisteredEvent', fields: [
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['recording_id', 'address'],
    ['routed_stake_id', 'address'],
    ['stake_id', 'address'],
    ['pool_id', 'address'],
    ['principal_value', 'u64'],
    ['registration_count_before', 'u64'],
    ['registration_count_after', 'u64'],
    ['pool_staked_shares_before', 'u64'],
    ['pool_staked_shares_after', 'u64'],
    ['pool_balance', 'u64'],
    ['pool_cumulative_reward_per_share', 'u256'],
    ['registration_debt', 'u256'],
    ['pool_carry', 'u128'],
    ['pool_cumulative_deposits', 'u128'],
  ] },
  { path: 'actions.compositionRoutedStake.unregistered', name: 'CompositionRoutedStakeUnregisteredEvent', fields: [
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['recording_id', 'address'],
    ['routed_stake_id', 'address'],
    ['stake_id', 'address'],
    ['pool_id', 'address'],
    ['principal_value', 'u64'],
    ['registration_count_before', 'u64'],
    ['registration_count_after', 'u64'],
    ['pool_staked_shares_before', 'u64'],
    ['pool_staked_shares_after', 'u64'],
    ['pool_balance', 'u64'],
    ['pool_cumulative_reward_per_share', 'u256'],
    ['registration_debt', 'u256'],
    ['pool_carry', 'u128'],
    ['pool_cumulative_deposits', 'u128'],
    ['forfeited_scaled_reward', 'u256'],
  ] },
  { path: 'actions.compositionRoutedStake.unstaked', name: 'CompositionRoutedStakeUnstakedEvent', fields: [
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['routed_stake_id', 'address'],
    ['stake_id', 'address'],
    ['principal_value', 'u64'],
  ] },
  { path: 'actions.compositionRoutedStake.restaked', name: 'CompositionRoutedStakeRestakedEvent', fields: [
    ['composition_id', 'address'],
    ['admin_cap_id', 'address'],
    ['routed_stake_id', 'address'],
    ['stake_id', 'address'],
    ['sender', 'address'],
    ['principal_value', 'u64'],
    ['registration_count', 'u64'],
  ] },
  { path: 'actions.releaseRevenueDistributor.coinsReceived', name: 'ReleaseCoinsReceivedEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['coin_ids', 'address[]'],
    ['amount', 'u64'],
  ] },
  { path: 'actions.releaseRevenueDistributor.fundsRedeemed', name: 'ReleaseFundsRedeemedEvent', fields: [
    ['release_id', 'address'],
    ['admin_cap_id', 'address'],
    ['amount', 'u64'],
  ] },
  { path: 'actions.releaseRevenueDistributor.trackRevenueDistributed', name: 'ReleaseTrackRevenueDistributedEvent', fields: [
    ['release_id', 'address'],
    ['track_index', 'u64'],
    ['composition_id', 'address'],
    ['recording_id', 'address'],
    ['split_bps', 'u16'],
    ['total_input', 'u64'],
    ['amount', 'u64'],
  ] },
  { path: 'actions.releaseRevenueDistributor.revenueDistributed', name: 'ReleaseRevenueDistributedEvent', fields: [
    ['release_id', 'address'],
    ['track_count', 'u64'],
    ['total_input', 'u64'],
    ['total_distributed', 'u64'],
    ['remainder', 'u64'],
  ] },
  { path: 'actions.partyWallet.objectReceived', name: 'ObjectReceivedEvent', fields: [
    ['party_id', 'address'],
    ['object_id', 'address'],
  ] },
  { path: 'actions.partyWallet.coinsReceived', name: 'CoinsReceivedEvent', fields: [
    ['party_id', 'address'],
    ['coin_ids', 'address[]'],
    ['amount', 'u64'],
    ['coins', 'u64'],
  ] },
  { path: 'actions.partyWallet.fundsRedeemed', name: 'FundsRedeemedEvent', fields: [
    ['party_id', 'address'],
    ['amount', 'u64'],
  ] },
  { path: 'plugins.compositionRoyaltyPool.installed', name: 'CompositionRoyaltyPoolPluginInstalledEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['vault_admin_cap_id', 'address'],
    ['authorized_plugins_id', 'address'],
    ['authorized_plugin_count', 'u64'],
    ['installed', 'bool'],
  ] },
  { path: 'plugins.compositionRoyaltyPool.uninstalled', name: 'CompositionRoyaltyPoolPluginUninstalledEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['vault_admin_cap_id', 'address'],
    ['authorized_plugins_id', 'address'],
    ['authorized_plugin_count', 'u64'],
    ['installed', 'bool'],
  ] },
  { path: 'plugins.compositionRoyaltyPool.capabilityBorrowed', name: 'CompositionVaultCapabilityBorrowedEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['composition_id', 'address'],
    ['pool_id', 'address'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
  ] },
  { path: 'plugins.compositionRoyaltyPool.coinsDeposited', name: 'CompositionCoinsDepositedEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['composition_id', 'address'],
    ['pool_id', 'address'],
    ['pool_balance_before', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares', 'u64'],
    ['reward_per_share_before', 'u256'],
    ['reward_per_share_after', 'u256'],
    ['carry_before', 'u128'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_before', 'u128'],
    ['cumulative_deposits_after', 'u128'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
    ['coin_ids', 'address[]'],
  ] },
  { path: 'plugins.compositionRoyaltyPool.fundsDeposited', name: 'CompositionFundsDepositedEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['composition_id', 'address'],
    ['pool_id', 'address'],
    ['pool_balance_before', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares', 'u64'],
    ['reward_per_share_before', 'u256'],
    ['reward_per_share_after', 'u256'],
    ['carry_before', 'u128'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_before', 'u128'],
    ['cumulative_deposits_after', 'u128'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
    ['amount', 'u64'],
  ] },
  { path: 'plugins.recordingRoyaltyPool.installed', name: 'RecordingRoyaltyPoolPluginInstalledEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['vault_admin_cap_id', 'address'],
    ['authorized_plugins_id', 'address'],
    ['authorized_plugin_count', 'u64'],
    ['installed', 'bool'],
  ] },
  { path: 'plugins.recordingRoyaltyPool.uninstalled', name: 'RecordingRoyaltyPoolPluginUninstalledEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['vault_admin_cap_id', 'address'],
    ['authorized_plugins_id', 'address'],
    ['authorized_plugin_count', 'u64'],
    ['installed', 'bool'],
  ] },
  { path: 'plugins.recordingRoyaltyPool.capabilityBorrowed', name: 'RecordingVaultCapabilityBorrowedEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['pool_id', 'address'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
  ] },
  { path: 'plugins.recordingRoyaltyPool.coinsDeposited', name: 'RecordingCoinsDepositedEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['pool_id', 'address'],
    ['pool_balance_before', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares', 'u64'],
    ['reward_per_share_before', 'u256'],
    ['reward_per_share_after', 'u256'],
    ['carry_before', 'u128'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_before', 'u128'],
    ['cumulative_deposits_after', 'u128'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
    ['coin_ids', 'address[]'],
  ] },
  { path: 'plugins.recordingRoyaltyPool.fundsDeposited', name: 'RecordingFundsDepositedEvent', fields: [
    ['vault_id', 'address'],
    ['cap_id', 'address'],
    ['recording_id', 'address'],
    ['composition_id', 'address'],
    ['pool_id', 'address'],
    ['pool_balance_before', 'u64'],
    ['pool_balance_after', 'u64'],
    ['staked_shares', 'u64'],
    ['reward_per_share_before', 'u256'],
    ['reward_per_share_after', 'u256'],
    ['carry_before', 'u128'],
    ['carry_after', 'u128'],
    ['cumulative_deposits_before', 'u128'],
    ['cumulative_deposits_after', 'u128'],
    ['active', 'bool'],
    ['capability_available', 'bool'],
    ['amount', 'u64'],
  ] },
  { path: 'plugins.releaseRevenueDistributor.installed', name: 'ReleaseRevenueDistributorPluginInstalledEvent', fields: [
    ['vault_id', 'address'],
    ['vault_admin_cap_id', 'address'],
    ['release_admin_cap_id', 'address'],
    ['vault_active', 'bool'],
    ['authorized_before', 'bool'],
    ['authorized_after', 'bool'],
    ['authorized_plugin_count_before', 'u64'],
    ['authorized_plugin_count_after', 'u64'],
  ] },
  { path: 'plugins.releaseRevenueDistributor.uninstalled', name: 'ReleaseRevenueDistributorPluginUninstalledEvent', fields: [
    ['vault_id', 'address'],
    ['vault_admin_cap_id', 'address'],
    ['release_admin_cap_id', 'address'],
    ['vault_active', 'bool'],
    ['authorized_before', 'bool'],
    ['authorized_after', 'bool'],
    ['authorized_plugin_count_before', 'u64'],
    ['authorized_plugin_count_after', 'u64'],
  ] },
  { path: 'plugins.releaseRevenueDistributor.coinsDistributed', name: 'ReleaseRevenueCoinsDistributedEvent', fields: [
    ['vault_id', 'address'],
    ['release_admin_cap_id', 'address'],
    ['release_id', 'address'],
    ['input_coin_count', 'u64'],
    ['input_coin_ids', 'address[]'],
  ] },
  { path: 'plugins.releaseRevenueDistributor.fundsDistributed', name: 'ReleaseRevenueFundsDistributedEvent', fields: [
    ['vault_id', 'address'],
    ['release_admin_cap_id', 'address'],
    ['release_id', 'address'],
    ['accumulator_root_id', 'address'],
    ['settled_input', 'u64'],
  ] },
  { path: 'products.record.destroyed', name: 'RecordDestroyedEvent', fields: [
    ['record_id', 'address'],
    ['release_id', 'address'],
    ['pressing_id', 'address'],
    ['edition', 'u16'],
    ['number', 'u32'],
    ['purchase_currency', 'string'],
    ['purchase_price', 'u64'],
    ['purchased_by', 'address'],
    ['purchased_timestamp_ms', 'u64'],
  ] },
  { path: 'products.record.legacy.created', name: 'RecordCreatedEvent', fields: [
    ['record_id', 'address'],
    ['release_id', 'address'],
    ['pressing_id', 'address'],
    ['edition', 'u16'],
    ['number', 'u32'],
  ] },
  { path: 'products.pressing.created', name: 'PressingCreatedEvent', fields: [
    ['pressing_id', 'address'],
    ['release_id', 'address'],
    ['pressing_admin_cap_id', 'address'],
    ['release_admin_cap_id', 'address'],
    ['edition', 'u16'],
    ['supply', 'u32'],
    ['max_supply', 'option_u32'],
    ['distributors', 'string[]'],
  ] },
  { path: 'products.pressing.purchased', name: 'RecordPurchasedEvent', fields: [
    ['record_id', 'address'],
    ['release_id', 'address'],
    ['pressing_id', 'address'],
    ['edition', 'u16'],
    ['number', 'u32'],
    ['purchase_currency', 'string'],
    ['purchase_price', 'u64'],
    ['purchased_by', 'address'],
    ['purchased_timestamp_ms', 'u64'],
    ['distributor', 'string'],
    ['supply_before', 'u32'],
    ['supply_delta', 'u32'],
    ['supply_after', 'u32'],
    ['max_supply', 'option_u32'],
  ] },
  { path: 'products.pressing.shared', name: 'PressingSharedEvent', fields: [
    ['pressing_id', 'address'],
    ['release_id', 'address'],
    ['edition', 'u16'],
    ['supply', 'u32'],
    ['max_supply', 'option_u32'],
    ['distributors', 'string[]'],
  ] },
  { path: 'products.pressing.distributorAuthorized', name: 'PressingDistributorAuthorizedEvent', fields: [
    ['pressing_id', 'address'],
    ['release_id', 'address'],
    ['edition', 'u16'],
    ['pressing_admin_cap_id', 'address'],
    ['distributor', 'string'],
    ['authorized_before', 'bool'],
    ['authorized_after', 'bool'],
    ['distributor_count_before', 'u64'],
    ['distributor_count_after', 'u64'],
  ] },
  { path: 'products.pressing.distributorRevoked', name: 'PressingDistributorRevokedEvent', fields: [
    ['pressing_id', 'address'],
    ['release_id', 'address'],
    ['edition', 'u16'],
    ['pressing_admin_cap_id', 'address'],
    ['distributor', 'string'],
    ['authorized_before', 'bool'],
    ['authorized_after', 'bool'],
    ['distributor_count_before', 'u64'],
    ['distributor_count_after', 'u64'],
  ] },
  { path: 'products.pressing.legacy.distributorAuthorized', name: 'DistributorAuthorizedEvent', fields: [
    ['pressing_id', 'address'],
    ['distributor', 'type_name'],
  ] },
  { path: 'products.pressing.legacy.distributorRevoked', name: 'DistributorRevokedEvent', fields: [
    ['pressing_id', 'address'],
    ['distributor', 'type_name'],
  ] },
  { path: 'products.listing.created', name: 'ListingCreatedEvent', fields: [
    ['listing_id', 'address'],
    ['release_id', 'address'],
    ['pressing_id', 'address'],
    ['pressing_admin_cap_id', 'address'],
    ['pricing_is_fixed', 'bool'],
    ['price', 'u64'],
    ['enabled', 'bool'],
  ] },
  { path: 'products.listing.shared', name: 'ListingSharedEvent', fields: [
    ['listing_id', 'address'],
    ['release_id', 'address'],
    ['pressing_id', 'address'],
    ['pricing_is_fixed', 'bool'],
    ['price', 'u64'],
    ['enabled', 'bool'],
  ] },
  { path: 'products.listing.priceChanged', name: 'ListingPriceChangedEvent', fields: [
    ['listing_id', 'address'],
    ['release_id', 'address'],
    ['pressing_id', 'address'],
    ['pressing_admin_cap_id', 'address'],
    ['pricing_is_fixed_before', 'bool'],
    ['price_before', 'u64'],
    ['pricing_is_fixed_after', 'bool'],
    ['price_after', 'u64'],
    ['enabled', 'bool'],
  ] },
  { path: 'products.listing.stateChanged', name: 'ListingStateChangedEvent', fields: [
    ['listing_id', 'address'],
    ['release_id', 'address'],
    ['pressing_id', 'address'],
    ['pressing_admin_cap_id', 'address'],
    ['pricing_is_fixed', 'bool'],
    ['price', 'u64'],
    ['enabled_before', 'bool'],
    ['enabled_after', 'bool'],
  ] },
  { path: 'products.listing.sold', name: 'RecordSoldEvent', fields: [
    ['listing_id', 'address'],
    ['record_id', 'address'],
    ['release_id', 'address'],
    ['pressing_id', 'address'],
    ['edition', 'u16'],
    ['number', 'u32'],
    ['purchase_currency', 'bytes'],
    ['purchase_price', 'u64'],
    ['purchased_by', 'address'],
    ['purchased_timestamp_ms', 'u64'],
    ['pricing_is_fixed', 'bool'],
    ['price', 'u64'],
    ['enabled', 'bool'],
    ['distributor', 'bytes'],
    ['supply_before', 'u32'],
    ['supply_delta', 'u32'],
    ['supply_after', 'u32'],
    ['has_max_supply', 'bool'],
    ['max_supply', 'u32'],
    ['payment_recipient', 'address'],
    ['proceeds_amount', 'u64'],
  ] },
  { path: "actions.pay.paymentSent", name: "PaymentSentEvent", fields: [
    ["target_id", "address"],
    ["target_type", "type_name"],
    ["payer", "address"],
    ["value", "u64"],
    ["metadata", "bytes"],
    ["paid_at_ms", "u64"],
  ] },
];

function schemaFor(name: string, fields: readonly WireField[]) {
  const schemas: Record<WireToken, any> = {
    address: bcs.Address,
    bool: bcs.bool(),
    u8: bcs.u8(),
    u16: bcs.u16(),
    u32: bcs.u32(),
    u64: bcs.u64(),
    u128: bcs.u128(),
    u256: bcs.u256(),
    string: bcs.string(),
    bytes: bcs.vector(bcs.u8()),
    "bytes[]": bcs.vector(bcs.vector(bcs.u8())),
    "bytes[][]": bcs.vector(bcs.vector(bcs.vector(bcs.u8()))),
    "address[]": bcs.vector(bcs.Address),
    "string[]": bcs.vector(bcs.string()),
    "u64[]": bcs.vector(bcs.u64()),
    "u256[]": bcs.vector(bcs.u256()),
    option_u32: bcs.option(bcs.u32()),
    option_bytes: bcs.option(bcs.vector(bcs.u8())),
    type_name: bcs.struct("TypeName", { name: bcs.string() }),
  };
  return bcs.struct(name, Object.fromEntries(fields.map(([field, type]) => [field, schemas[type]])) as any);
}

function valueFor(type: WireToken, eventIndex: number, fieldIndex: number): unknown {
  const n = eventIndex * 31 + fieldIndex + 1;
  const address = (byte: number) => "0x" + byte.toString(16).padStart(2, "0").repeat(32);
  const u64 = (offset: number) => (9007199254740000n + BigInt(offset)).toString();
  switch (type) {
    case "address": return address((n % 200) + 1);
    case "bool": return n % 2 === 0;
    case "u8": return (n % 200) + 1;
    case "u16": return (n % 60000) + 100;
    case "u32": return (n % 100000) + 1000;
    case "u64": return u64(n);
    case "u128": return (1n << 100n | BigInt(n)).toString();
    case "u256": return (1n << 200n | BigInt(n)).toString();
    case "string": return `wire-${eventIndex}-${fieldIndex}`;
    case "bytes": return [n % 250, (n + 1) % 250, (n + 2) % 250];
    case "bytes[]": return [[n % 250, (n + 1) % 250], [(n + 2) % 250, (n + 3) % 250]];
    case "bytes[][]": return [[[n % 250, (n + 1) % 250]], [[(n + 2) % 250, (n + 3) % 250]]];
    case "address[]": return [address((n % 200) + 1), address(((n + 1) % 200) + 1)];
    case "string[]": return [`wire-${eventIndex}-${fieldIndex}-a`, `wire-${eventIndex}-${fieldIndex}-b`];
    case "u64[]": return [u64(n), u64(n + 1)];
    case "u256[]": return [(1n << 200n | BigInt(n)).toString(), (1n << 200n | BigInt(n + 1)).toString()];
    case "option_u32": return (n % 100000) + 1000;
    case "option_bytes": return [n % 250, (n + 1) % 250];
    case "type_name": return { name: `0x${((n % 200) + 1).toString(16).padStart(2, "0")}::wire::Type${n}` };
  }
}

function parserAt(path: string): (bytes: Uint8Array) => unknown {
  let value: unknown = platformEventParsers;
  for (const segment of path.split(".")) value = (value as Record<string, unknown>)[segment];
  expect(typeof value).toBe("function");
  return value as (bytes: Uint8Array) => unknown;
}

for (const [eventIndex, fixture] of EVENT_WIRE_FIXTURES.entries()) {
  test(`independent wire fixture ${eventIndex + 1}/${EVENT_WIRE_FIXTURES.length}: ${fixture.path}`, () => {
    const expected = Object.fromEntries(fixture.fields.map(([field, type], fieldIndex) => [field, valueFor(type, eventIndex, fieldIndex)]));
    const bytes = schemaFor(fixture.name, fixture.fields).serialize(expected).toBytes();
    if (fixture.name === "ReleaseTrackCoverArtSetEvent" || fixture.name === "ReleaseTrackCoverArtUnsetEvent") {
      // Keep the independent flat wire fixture: nesting the album snapshot
      // changes the decoded JSON shape, while preserving every BCS byte.
      const album: Record<string, unknown> = {};
      for (const field of Object.keys(expected)) {
        if (!field.startsWith("album_")) continue;
        album[field.slice("album_".length)] = expected[field];
        delete expected[field];
      }
      expect(Object.keys(album)).toHaveLength(10);
      expected.album = album;
    }
    const decoded = fixture.name === "PaymentSentEvent"
      ? platformEventParsers.actions.pay.paymentSent(bcs.vector(bcs.u8()))(bytes)
      : parserAt(fixture.path)(bytes);
    expect(decoded).toEqual(expected);
  });
}

test("wire fixture inventory covers all canonical event codecs, including generic pay metadata", () => {
  expect(EVENT_WIRE_FIXTURES).toHaveLength(135);
  expect(new Set(EVENT_WIRE_FIXTURES.map((fixture) => fixture.path)).size).toBe(135);
});
